"""Trusted channel identity, employee authority, and durable queue storage."""

from .builtin_assistant import (
    BuiltinAssistantPolicy,
    BuiltinAssistantPolicyRevisionConflict,
    BuiltinAssistantPolicyUnavailable,
    DEFAULT_BUILTIN_ASSISTANT_NICKNAME,
    builtin_assistant_personalization_payload,
    resolve_builtin_assistant_personalization,
    resolve_builtin_assistant_policy,
    update_builtin_assistant_personalization,
    update_builtin_assistant_policy,
)
from .crypto import ChannelCrypto, Keyring
from .employees import (
    BuiltinEmployeeProtected,
    EmployeeProfileRevisionConflict,
    FeishuCredentialRevisionConflict,
    create_employee,
    employee_profile_fingerprint,
    ensure_employee_feishu_conversation_binding,
    list_employees,
    reconcile_employee_workspaces,
    register_employee_feishu_binding,
    reject_builtin_employee_mutation,
    resolve_employee,
    rollover_employee_sessions,
    resolve_employee_collaboration_policy,
    resolve_employee_feishu_binding,
    resolve_employee_feishu_credentials,
    resolve_employee_profile,
    rotate_employee_feishu_credentials,
    set_employee_feishu_binding_status,
    set_employee_status,
    update_employee_collaboration_policy,
    update_employee_profile,
)
from .models import (
    Employee,
    EmployeeChannelBinding,
    EmployeeCollaborationPolicy,
    EmployeeProfile,
    RegisteredChannel,
    ResolvedChannelOwner,
    ResolvedConnectorAccount,
)
from .owner_resolution import resolve_binding, resolve_connector_account
from .registration import (
    ChannelIdentityOwnershipConflict,
    activate_weixin_identity,
    ensure_owner_binding,
    register_connector_binding_for_owner,
    register_weixin_identity,
    register_weixin_identity_for_owner,
)
from .store import ChannelIdentityStore

__all__ = [
    "BuiltinAssistantPolicy",
    "BuiltinAssistantPolicyRevisionConflict",
    "BuiltinAssistantPolicyUnavailable",
    "ChannelCrypto",
    "ChannelIdentityOwnershipConflict",
    "ChannelIdentityStore",
    "BuiltinEmployeeProtected",
    "Employee",
    "EmployeeChannelBinding",
    "EmployeeCollaborationPolicy",
    "EmployeeProfile",
    "EmployeeProfileRevisionConflict",
    "DEFAULT_BUILTIN_ASSISTANT_NICKNAME",
    "FeishuCredentialRevisionConflict",
    "Keyring",
    "RegisteredChannel",
    "ResolvedChannelOwner",
    "ResolvedConnectorAccount",
    "activate_weixin_identity",
    "builtin_assistant_personalization_payload",
    "create_employee",
    "employee_profile_fingerprint",
    "ensure_employee_feishu_conversation_binding",
    "ensure_owner_binding",
    "list_employees",
    "reconcile_employee_workspaces",
    "register_connector_binding_for_owner",
    "register_employee_feishu_binding",
    "reject_builtin_employee_mutation",
    "register_weixin_identity",
    "register_weixin_identity_for_owner",
    "resolve_binding",
    "resolve_builtin_assistant_personalization",
    "resolve_builtin_assistant_policy",
    "resolve_connector_account",
    "resolve_employee",
    "resolve_employee_collaboration_policy",
    "resolve_employee_feishu_binding",
    "resolve_employee_feishu_credentials",
    "resolve_employee_profile",
    "rollover_employee_sessions",
    "rotate_employee_feishu_credentials",
    "set_employee_feishu_binding_status",
    "set_employee_status",
    "update_builtin_assistant_personalization",
    "update_builtin_assistant_policy",
    "update_employee_collaboration_policy",
    "update_employee_profile",
]
